services:
  kafka:
    image: apache/kafka:latest
    container_name: broker
    hostname: kafka
    ports:
      - "9092:9092"  # Expose Kafka broker port
    environment:
      KAFKA_NODE_ID: 1  # Unique identifier for the Kafka node
      KAFKA_PROCESS_ROLES: broker,controller  # Roles assigned to the Kafka process
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093  # Define listeners for broker and controller
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092  # Advertised listeners for external access
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER  # Listener names for the controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT  # Security protocol mapping
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093  # Quorum voters for the controller
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  # Replication factor for the offsets topic
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1  # Replication factor for the transaction state log
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1  # Minimum in-sync replicas for the transaction state log
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0  # Initial rebalance delay for consumer groups
      KAFKA_NUM_PARTITIONS: 3  # Number of partitions for the topics
    networks:
      - default  # Attach to the default network

  redis:
    image: redis:latest
    container_name: redis-broker
    ports:
      - "6379:6379"  # Expose Redis port
    networks:
      - default  # Attach to the default network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    ports:
      - "8081:8081"  # Expose Redis Commander port
    environment:
      - REDIS_HOST=redis  # Redis host configuration
      - REDIS_PORT=6379  # Redis port configuration
    depends_on:
      - redis  # Ensure Redis service is started before Redis Commander
    networks:
      - default  # Attach to the default network

networks:
  default:
    driver: bridge  # Use bridge network driver
    driver_opts:
      com.docker.network.enable_ipv6: "false"  # Disable IPv6 for the network