services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_document
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  document_message:
    build: 
      context: .
    container_name: document_message
    restart: always
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"
    environment:
      BROKER_URL: amqp://guest:guest@rabbitmq:5672/
      DOCUMENT_QUEUE: document_messages
